# Generated by Django 3.1.6 on 2021-02-24 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('endpointApp', '0004_auto_20210224_2148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='dept',
        ),
        migrations.RemoveField(
            model_name='teacherprofile',
            name='dept',
        ),
        migrations.DeleteModel(
            name='Departement',
        ),
    ]
